'use client';

import Footer from '@/components/Footer';

export default function TermsAndConditions() {
  return (
    <section>
      <div>
        <h1>Terms and Conditions</h1>
  <p>Last updated: June 7, 2025</p>

  <p>Welcome to <strong>Agentverse</strong>. These terms and conditions outline the rules and regulations for the use of Agentverse's services, including any AI-powered features, chat interfaces, and API integrations provided through our platform.</p>

  <h2>1. Acceptance of Terms</h2>
  <p>By accessing this website or using our services, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree with any part of these terms, you must not use our platform.</p>

  <h2>2. Services</h2>
  <p>Agentverse provides AI-based tools, chat functionality, and related APIs. We reserve the right to modify or discontinue the service (or any part of it) at any time without notice.</p>

  <h2>3. User Responsibilities</h2>
  <ul>
    <li>You agree to use Agentverse only for lawful purposes.</li>
    <li>You must not attempt to gain unauthorized access to any part of the system.</li>
    <li>You are responsible for any activity that occurs under your account.</li>
  </ul>

  <h2>4. AI Usage Disclaimer</h2>
  <p>The AI-generated content is for informational and experimental purposes only. Agentverse does not guarantee the accuracy, reliability, or legality of content generated by the AI models integrated into our platform.</p>

  <h2>5. Data Privacy</h2>
  <p>Your data is handled in accordance with our <a href="/privacy-policy">Privacy Policy</a>. You are responsible for ensuring that any data you provide or store through our services complies with applicable privacy laws.</p>

  <h2>6. Limitation of Liability</h2>
  <p>Agentverse shall not be liable for any indirect, incidental, or consequential damages resulting from the use or inability to use the service, including but not limited to reliance on any AI-generated output.</p>

  <h2>7. Termination</h2>
  <p>We reserve the right to suspend or terminate your access to the service at our sole discretion, with or without notice, for conduct that we believe violates these Terms.</p>

  <h2>8. Governing Law</h2>
  <p>These Terms shall be governed by and interpreted in accordance with the laws of your applicable jurisdiction.</p>

  <h2>9. Contact Us</h2>
  <p>If you have any questions about these Terms, you can contact us at <a href="mailto:dakshg393@gmail.com">mail</a>.</p>

      </div>
      <Footer />
    </section>
  );
}
